services:
  mariadb:
    image: mariadb:11
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -p$${MARIADB_ROOT_PASSWORD} --silent || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 40s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["sh","-c","exec redis-server --requirepass \"$REDIS_PASSWORD\""]
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$REDIS_PASSWORD\" ping | grep -q PONG"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s
    restart: unless-stopped

  backend:
    image: sangwon0410/nongchukya-backend:${BACK_TAG}
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "${EXTERNAL_PORT}:8080"
    environment:
      APP_PROFILE: ${APP_PROFILE}
      SPRING_DATASOURCE_URL: jdbc:mariadb://${DB_HOST}:3306/${DB_NAME}?useUnicode=true&characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PORT: "${REDIS_PORT}"
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info
      MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
    restart: unless-stopped

  frontend:
    image: sangwon0410/nongchukya-frontend:${FRONT_TAG}
    depends_on:
      backend:
        condition: service_started
    ports:
      - "5173:80"
    restart: unless-stopped
