apiVersion: v1
kind: Service
metadata:
  name: matching-redis-service
spec:
  type: ClusterIP
  selector:
    app: matching-redis-app
  ports:
  - name: redis-port
    port: 6379
    targetPort: 6379
