apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-blue-label
      version: blue
  template:
    metadata:
      labels:
        app: backend-blue-label
        version: blue
    spec:
      containers:
      - name: backend-blue
        image: nongchukya/backend
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
            
        ports:
        - containerPort: 8080
