apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-blue-label
      version: blue
  template:
    metadata:
      labels:
        app: frontend-blue-label
        version: blue
    spec:
      containers:
      - name: frontend-blue
        image: nongchukya/frontend
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 5173
