server:
  port: 8087
  # .
logging:
  level:
    '[org.springframework.web]': debug
    '[org.springframework.security]': debug
    '[org.mariadb.jdbc.client.impl]': debug
    '[org.springframework.data.redis]': debug
    '[io.lettuce.core]': debug