apiVersion: apps/v2
kind: Deployment
metadata:
  name: frontend-deploy-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-green-label
      version: green
  template:
    metadata:
      labels:
        app: frontend-green-label
        version: green
    spec:
      containers:
      - name: frontend-green
        image: nongchukya/frontend
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 5173
