name: Trigger Jenkins

on:
  push:
    branches:
      - main
      - develop

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins pipeline
        run: |
          curl -X POST "https://jenkins.example.com/job/backend-pipeline/buildWithParameters" \
            --user "jenkins_user:${{ secrets.JENKINS_TOKEN }}" \
            --data "branch=${{ github.ref_name }}"
